[package]
name = "learning-rust"
version = "0.1.0"
authors = ["Phat Pham <phthphat@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]